copyright:
docs_dir: build/linkml-docs
nav:
  - Home: index.md
  - About: about.md
  - Schemas:
    - Thing (unreleased): s/thing/unreleased/index.md
    - Properties (unreleased): s/properties/unreleased/index.md
    - Identifiers (unreleased): s/identifiers/unreleased/index.md
    - Provenance (unreleased): s/prov/unreleased/index.md
    - Distribution (unreleased): s/distribution/unreleased/index.md
    - DataLad dataset (unreleased): s/datalad-dataset/unreleased/index.md
    - Scientific data distribution (unreleased): s/sdd/unreleased/index.md
plugins:
  - mermaid2
  - redirects:
      redirect_maps:
          # map unversioned URLs to the latest version
          's/thing/index.md': 's/thing/unreleased/index.md'
          's/properties/index.md': 's/properties/unreleased/index.md'
          's/identifiers/index.md': 's/identifiers/unreleased/index.md'
          's/prov/index.md': 's/prov/unreleased/index.md'
          's/distribution/index.md': 's/distribution/unreleased/index.md'
          's/datalad-dataset/index.md': 's/datalad-dataset/unreleased/index.md'
          's/sdd/index.md': 's/sdd/unreleased/index.md'
  - search
site_author: DataLad Team
site_description:
site_dir: build/mkdocs-site
site_name: DataLad Concepts
site_url: !ENV [SITEURL, 'https://concepts.datalad.org']
# false, because we have many doc files that are not mentioned in "nav"
strict: false
theme:
  name: mkdocs
  locale: en
