copyright:
docs_dir: build/linkml-docs
nav:
  - Home: index.md
  - About: about.md
  - Schemas:
    - Distribution (unreleased): s/distribution/unreleased/index.md
    - Demo derived schema: s/derived-example/unreleased/index.md
plugins:
  - mermaid2
repo_url: https://github.com/psychoinformatics-de/datalad-concepts
site_author:
site_description:
site_dir: build/mkdocs-site
site_name: DataLad Concepts
site_url: !ENV [SITEURL, 'https://concepts.datalad.org']
# false, because we have many doc files that are not mentioned in "nav"
strict: false
theme:
  name: gitbook
  locale: en
