schema: src/thing/unreleased.yaml
target_class: ValueSpecification
data_sources:
  - src/thing/unreleased/examples/ValueSpecification-01-minimal.yaml
  - src/thing/unreleased/examples/ValueSpecification-02-quantitative-measurement.yaml
plugins:
  JsonschemaValidationPlugin:
    closed: true
    include_range_class_descendants: false
  RecommendedSlotsPlugin:
